defaults:
  - _self_
  - model: resnet50     # or resnet18 
  - optimizer: adam
  - optional dataset: imagenet # Makes dataset config optional
  - training: default
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - override hydra/launcher: basic

# Global configurations
seed: 42
device: "cuda"

# Paths configuration
paths:
  data_dir: ${oc.env:DATA_DIR,data}
  output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  checkpoint_dir: ${paths.output_dir}/checkpoints

# Runtime configurations
runtime:
  debug: false
  profile: false

image:
  path: "C:/Users/User/OneDrive/Desktop/Hydra/edited4.png"
  size: 224

preprocessing:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

hydra:
  sweeper:
    params:
      optimizer.params.lr: 0.001,0.0001,0.00001
      model: resnet18,resnet50 